# Generated by Django 3.2.6 on 2021-09-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show',
            field=models.SmallIntegerField(default=1),
        ),
    ]
