# Generated by Django 3.2.6 on 2021-09-04 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='show',
        ),
    ]
