# Generated by Django 3.2.6 on 2021-09-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='deleteFlag',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='isHome',
            field=models.SmallIntegerField(default=1),
        ),
    ]
